main: org.dragonet.bukkit.lnationsions.LegendaryNationsPlugin
version: 1.2
name: LegendaryNations
author: DefinitlyEvil
depend: ["MenuAPI"]
commands:
  land:
    description: "Open the nations map to manage your lnations. "
